# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiderMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riderNo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='riderride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rideNo', models.CharField(max_length=30)),
                ('secs', models.IntegerField()),
                ('watts', models.IntegerField()),
                ('heartRate', models.IntegerField()),
                ('riderNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.RiderMaster')),
            ],
        ),
    ]
