# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 22:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_fitfilemasterupload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fitfilemasterupload',
            old_name='docfile',
            new_name='f',
        ),
    ]
