# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20160407_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitfilemasterupload',
            name='f',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
