# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20160407_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderride',
            name='speed',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
