# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20160414_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='riderride',
            name='riderNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.ridermaster'),
        ),
    ]
