# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20160414_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderride',
            name='elevation',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='riderride',
            name='riderNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.ridermaster'),
        ),
    ]
