# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20160418_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderride',
            name='riderNo',
            field=models.CharField(max_length=30),
        ),
    ]
