# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20160418_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='limitwattsrider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riderNo', models.CharField(max_length=20)),
                ('secs', models.IntegerField()),
                ('watts', models.IntegerField()),
            ],
        ),
    ]
